<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nreacht3"
 *
 * Auto generated by Extension Builder 2015-01-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'nreach_t3_base',
    'description' => 'Base extension for all nreach activity',
	'category' => 'be',
	'author' => '',
	'author_email' => 'johnny@nreach.io',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
            'typo3' => '8.6.0-8.9.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
